# Generated by Django 3.0.4 on 2020-05-12 13:22

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='cover',
        ),
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(default=1, storage=django.core.files.storage.FileSystemStorage(location='/media/images'), upload_to=''),
            preserve_default=False,
        ),
    ]
